baseURL: https://ahenaor.github.io/
languageCode: es-co
title: ALEJO HENAO
theme: PaperMod
defaultcontentlanguage: es


menu:
  main:
  - identifier: about
    name: Sobre mi
    title: about
    url: /about/
    weight: 1
  - identifier: til
    name: Today-I-Learned
    title: til
    url: /til/
    weight: 2
  - identifier: categories
    name: Categorias
    title: categorias
    url: categories/
    weight: 3
  - identifier: tags
    name: Etiquetas
    title: tags
    url: tags/
    weight: 4
  - identifier: search
    name: Buscar
    title: search
    url: /search/
    weight: 5

params:
  defaultTheme: dark
  socialIcons:
    - name: email
      url: 'mailto:ahenaor@unal.edu.co'
    - name: linkedin
      url: 'https://www.linkedin.com/in/ahenaor'
    - name: github
      url: 'https://github.com/ahenaor'
    - name: twitter
      url: 'https://twitter.com/AlejoHenaoR'
  profileMode:
    enabled: true
    title: 'Hola, soy Alejo Henao.'
    subtitle: Puedes encontrarme en varios lugares en Internet.
  fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 1
        keys: ["title", "permalink", "summary", "content"]
  ShowShareButtons: true

outputs:
    home:
      - HTML
      - JSON
      - RSS

taxonomies:
    category: categories
    tag: tags
    series: series


